[databases]
# Format: dbname = host=postgres_host port=5432 dbname=postgres_db
* = dbname=lmsdb host=ls-9488e568a46965e62050e0c432df87edfcaf0eeb.c1qqko2w6405.ap-south-1.rds.amazonaws.com port=5432

[pgbouncer]
logfile = /opt/bitnami/pgbouncer/logs/pgbouncer.log
pidfile = /opt/bitnami/pgbouncer/tmp/pgbouncer.pid
listen_addr = 0.0.0.0
listen_port = 6432
auth_type = md5
auth_file = /opt/bitnami/pgbouncer/conf/userlist.txt
pool_mode = session
max_client_conn = 100
default_pool_size = 20