import shield from "./shield";

const resolvers = {
  Query: {
    signin: shield,
    signout: shield,
    exist: shield,
    verify: shield,
    user: shield,
    users: shield,
    enums:shield,
    country: shield,
    countries: shield,
    state: shield,
    states: shield,
    city: shield,
    cities: shield,
    category: shield,
    categories: shield,
    course: shield,
    courses: shield,
    schedule: shield,
    schedules: shield,
    module: shield,
    modules: shield,
    enrollment:shield,
    enrollments: shield,    
    meditation: shield,
    meditations: shield,
    short: shield,
    shorts: shield,
    resource: shield,
    resources: shield,
    scaredvibe: shield,
    scaredvibes: shield,
    referral: shield,
    referrals: shield,
    service: shield,
    services: shield,
    review: shield,
    reviews: shield,
    inquiry: shield,
    inquiries: shield,
    template: shield,
    templates: shield,
    page: shield,
    pages: shield,
    smtp: shield,
    /*     
    message: shield,
    messages: shield,           
    item: shield,    
    log: shield,
    logs: shield, */
  },
  Mutation: {
    signup: shield,
    addUser: shield,
    updateUser: shield,
    forgot: shield,
    reset: shield,
    changePassword: shield,
    addCategory: shield,
    updateCategory: shield,
    deleteCategory: shield,
    addCourse:shield,
    updateCourse: shield,
    publishCourse: shield,
    archiveCourse: shield,
    addSchedule: shield,
    updateSchedule: shield,
    deleteSchedule: shield,
    addModule: shield,
    updateModule: shield,
    deleteModule: shield,
    addShort: shield,
    updateShort: shield,
    deleteShort: shield,
    addMeditation: shield,
    updateMeditation: shield,
    deleteMeditation: shield,
    addResource: shield,
    updateResource: shield,
    deleteResource: shield,
    addScaredvibe: shield,
    updateScaredvibe: shield,
    deleteScaredvibe: shield,
    refer: shield,    
    deleteReferral: shield,
    addService: shield,
    updateService: shield,
    deleteService: shield,
    postReview: shield,
    deleteReview: shield,
    newInquiry: shield,
    updateInquiry: shield,
    deleteInquiry: shield,
    newTemplate: shield,
    updateTemplate: shield,
    deleteTemplate: shield,
    newPage: shield,
    updatePage: shield,
    deletePage: shield,
    addSmtp: shield,
    updateSmtp: shield,
  },
  /* Subscription: {
    access: {      
      subscribe: async (_: any, args: any, ctx: any) => {
        return await ctx.pubSub.subscribe('access')
      },
      resolve: async (payload: any) => {
        return await helper.access.get(payload);        
      },
    },
  }, */
};

export default resolvers;
