import shield from "./shield";

const resolvers = {
  Query: {
    signin: shield,
    signout: shield,
    exist: shield,
    verify: shield,
    user: shield,
    users: shield,
    enums:shield,
    country: shield,
    countries: shield,
    state: shield,
    states: shield,
    city: shield,
    cities: shield,
    category: shield,
    categories: shield,
    course: shield,
    courses: shield,
    schedule: shield,
    schedules: shield,
    module: shield,
    modules: shield,
    isEnrolled:shield,
    enrollment:shield,
    enrollments: shield,
    question:shield,
    questions: shield,
    option:shield,
    options: shield,
    meditation: shield,
    meditations: shield,
    short: shield,
    shorts: shield,
    resource: shield,
    resources: shield,
    sacredvibe: shield,
    sacredvibes: shield,
    referral: shield,
    referrals: shield,
    service: shield,
    services: shield,
    appointment: shield,
    appointments: shield,
    review: shield,
    reviews: shield,
    reactionCount: shield,
    reaction: shield,
    reactions: shield,
    inquiry: shield,
    inquiries: shield,
    order: shield,
    orders: shield,
    bought: shield,
    template: shield,
    templates: shield,
    page: shield,
    pages: shield,
    branding: shield,
    brandings: shield,
    setting: shield,
    settings: shield,
    smtp: shield,
    /*     
    message: shield,
    messages: shield,           
    item: shield,    
    log: shield,
    logs: shield, */
  },
  Mutation: {
    signup: shield,
    addUser: shield,
    updateUser: shield,
    deleteUser: shield,
    updateProfile: shield,
    forgot: shield,
    reset: shield,
    changePassword: shield,
    changeUserStatus: shield,
    verifyEmail: shield,
    addCategory: shield,
    updateCategory: shield,
    deleteCategory: shield,
    addCourse:shield,
    updateCourse: shield,
    publishCourse: shield,
    archiveCourse: shield,
    newQuestion: shield,
    updateQuestion: shield,
    deleteQuestion: shield,
    newOption: shield,
    updateOption: shield,
    deleteOption: shield,
    addSchedule: shield,
    updateSchedule: shield,
    changeScheduleStatus: shield,
    deleteSchedule: shield,
    addModule: shield,
    updateModule: shield,
    deleteModule: shield,
    changeEnrollmentStatus: shield,
    addShort: shield,
    updateShort: shield,
    deleteShort: shield,
    addMeditation: shield,
    updateMeditation: shield,
    changeMeditationStatus: shield,
    deleteMeditation: shield,
    addResource: shield,
    updateResource: shield,
    changeResourceStatus: shield,
    deleteResource: shield,
    addSacredvibe: shield,
    updateSacredvibe: shield,
    deleteSacredvibe: shield,
    refer: shield,    
    deleteReferral: shield,
    addService: shield,
    updateService: shield,
    deleteService: shield,
    uploadAuraReport: shield,
    postReview: shield,
    deleteReview: shield,
    newInquiry: shield,
    updateInquiry: shield,
    deleteInquiry: shield,
    newReaction: shield,
    updateReaction: shield,
    deleteReaction: shield,
    newOrder: shield,
    updateOrder: shield,
    deleteOrder: shield,
    newTemplate: shield,
    updateTemplate: shield,
    deleteTemplate: shield,
    newBranding: shield,
    updateBranding: shield,
    deleteBranding: shield,
    newPage: shield,
    updatePage: shield,
    deletePage: shield,
    newSetting: shield,
    updateSetting: shield,
    deleteSetting: shield,
    addSmtp: shield,
    updateSmtp: shield,
    enroll: shield,
    import: shield,
    track: shield,
  },
  /* Subscription: {
    access: {      
      subscribe: async (_: any, args: any, ctx: any) => {
        return await ctx.pubSub.subscribe('access')
      },
      resolve: async (payload: any) => {
        return await helper.access.get(payload);        
      },
    },
  }, */
};

export default resolvers;
