import 'package:app/services/aura.dart';
import 'package:app/services/branding.dart';
import 'package:app/services/common.dart';
import 'package:app/services/course.dart';
import 'package:app/services/enrollment.dart';
import 'package:app/services/identity.dart';
import 'package:app/services/meditation.dart';
import 'package:app/services/module.dart';
import 'package:app/services/order.dart';
import 'package:app/services/page.dart';
import 'package:app/services/qna.dart';
import 'package:app/services/reaction.dart';
import 'package:app/services/resource.dart';
import 'package:app/services/review.dart';
import 'package:app/services/sacredvibe.dart';
import 'package:app/services/schedule.dart';
import 'package:app/services/setting.dart';
import 'package:app/services/short.dart';
import 'package:app/services/storage.dart';
import 'package:app/services/user.dart';

class Service {
  static final aura = Aura();
  static final branding = Branding();
  static final common = Common();
  static final course = Course();
  static final enrollment = Enrollment();
  static final identity = Identity();
  static final module = Module();
  static final meditation = Meditation();
  static final order = Order();
  static final page = Page();
  static final qna = Qna();
  static final reaction = Reaction();
  static final resource = Resource();
  static final review = Review();
  static final sacredvibe = Sacredvibe();
  static final setting = Setting();
  static final short = Short();
  static final store = Storage();
  static final schedule = Schedule();
  static final user = User();
}
